### ISSUE TITLE
How to use on own server

### ISSUE THREAD

**Issue by danc91** [junhoyeo/NIKE-THE-DRAW-Calendar#33]
how can I use this on my own server, do you have install instructions?

**Comment by junhoyeo** [comment]
- You can run [parser.run.py](https://github.com/junhoyeo/NIKE-THE-DRAW-Calendar/blob/main/parser/run.py) with Python3. 
- Follow the steps on [update.yaml](https://github.com/junhoyeo/NIKE-THE-DRAW-Calendar/blob/main/.github/workflows/update.yaml) for futher actions.

**Comment by danc91** [comment]
are you able to send instructions for the update.yaml?

**Comment by junhoyeo** [comment]
You can follow the steps in the `update.yaml` to fetch draw data for yourself.
Can I get a explanation about the action you want to archive?
